# Server
server.port=8080

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/AuraHealthDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgre}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=YXVyYWhlYWx0aHNlY3JldGtleWZvcmxvY2FsZGV2ZWxvcG1lbnQyMDI0

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Seed data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true